#!/usr/bin/env bash
# install haproxy
sudo apt-get update
sudo apt-get -y install haproxy
config="frontend http
\tbind *:80
\tmode http
\tdefault_backend web-backend

backend web-backend
\tbalance roundrobin
\tserver 837-web-01 35.237.80.55:80 check
\tserver 837-web-02 35.231.185.233:80 check"
echo -e "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "ENABLED=1\n" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
